---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <gitea_fqdn>
  namespace: gitea
  annotations:
    avp.kubernetes.io/path: "argocd/secrets/data/gitea"
spec:
  secretName: wildcard-gitea-tls
  dnsNames:
    - <certificate_domain>
  issuerRef:
    name: issuer
    kind: ClusterIssuer
