---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cnpg.io/cluster: gitea
    cnpg.io/reload: "true"
  name: gitea-app
  namespace: gitea
stringData:
  password: <pg_app_password>
  pgpass: |
    gitea-rw:5432:app:app:<pg_app_password>
  username: app
type: kubernetes.io/basic-auth
