---
apiVersion: v1
kind: Secret
metadata:
  namespace: gitea
  name: gitea-admin-secret
  annotations:
    avp.kubernetes.io/path: "argocd/secrets/data/gitea"
type: Opaque
stringData:
  username: gitea_admin
  password: <gitea_admin_password>
